site_name: VaiPelaSombra
theme:
  name: material
  language: pt-BR
  logo: ../../img/logo_completa.png
  favicon: ../../img/logo_completa.png

  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra 


nav:
  - Sobre o projeto: index.md
  - 1. Análise de Requisitos: Requisitos/index.md
  - 2. FrontEnd: FrontEnd/index.md
  - 3. BackEnd: BackEnd/index.md

extra_css:
  - extra.css 