site_name: VaiPelaSombra
theme:
  name: material
  language: pt-BR
  logo: ../../img/logoVaiPelaSombra.jpeg
  favicon: ../../img/logopequenaVaiPelaSombra.jpeg

  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra 


nav:
  - Sobre o projeto: index.md
  - 1. Organização do Projeto: 
    - 1. Metodologias: OrganizacaoProjeto/index.md
    - 2. Termo de Abertura: OrganizacaoProjeto/TermodeAbertura/index.md
    - 3. Lean Inception: OrganizacaoProjeto/LeanInception/index.md
    - 4. BackLog: OrganizacaoProjeto/BackLog/index.md
    - 5. Planos e Monitoramento: 
      - 5.1. Plano de Comunicação: OrganizacaoProjeto/Planos/DocComunicacao.md
      - 5.2. Plano de Qualidade: OrganizacaoProjeto/Planos/planoqualidade.md
    - 6. Templates:
      - 6.1. Planning: OrganizacaoProjeto/Templates/Planning.md
      - 6.2. Retrospective: OrganizacaoProjeto/Templates/Retro.md
      - 6.3. Review: OrganizacaoProjeto/Templates/Review.md
    - 7. Prototipo: OrganizacaoProjeto/Prototipo/prototipo.md
    - 8. Riscos: 
      - 1. Tabelas de Riscos: OrganizacaoProjeto/Riscos/Riscos.md
      - 2. Mitigação de Riscos: OrganizacaoProjeto/Riscos/MitigacaoRiscos.md
    - 9. Gráfico de Gantt: OrganizacaoProjeto/gantt.md
  - 2. FrontEnd: 
    - 2.1. FrontEnd Estrutura: FrontEnd/index.md
    - 2.2. FrontEnd Dojos: FrontEnd/Dojos/index.md
    - 2.3. Guia de Estilo: FrontEnd/DocGuiaDeEstilo/index.md
  - 3. BackEnd: 
    - 3.1. BackEnd Estrutura: BackEnd/index.md
    - 3.2. BackEnd Dojos: BackEnd/Dojos/index.md
  - 4. Documento de Arquitetura: DocArquitetura/DocumentoArquitetura.md
  - 5. Políticas do Repositório:
    - 5.1. Guia de Contribuição: DocGuiaDeContribuicao/index.md
    - 5.2. Guia de Conduta: Politicas/guiaConduta.md
  - 6. Sprints:
    - 6.1 Acompanhamento de Valor Agregado: Sprints/DocValorAgregado/index.md
    - 6.2 Sprint 1: 
      - 6.2.1 Planning: Sprints/Sprint1/Planning.md
      - 6.2.2 Review: Sprints/Sprint1/Review.md
      - 6.2.3 Retrospective: Sprints/Sprint1/Retrospective.md
    - 6.3 Sprint 2: 
      - 6.3.1 Planning: Sprints/Sprint2/Planning.md
      - 6.3.2 Review: Sprints/Sprint2/Review.md
      - 6.3.3 Retrospective: Sprints/Sprint2/Retrospective.md
    - 6.4 Sprint 3: 
      - 6.4.1 Planning: Sprints/Sprint3/Planning.md
      - 6.4.2 Review: Sprints/Sprint3/Review.md
      - 6.4.3 Retrospective: Sprints/Sprint3/Retrospective.md
    - 6.5 Sprint 4: 
      - 6.5.1 Planning: Sprints/Sprint4/Planning.md
      - 6.5.2 Review: Sprints/Sprint4/Review.md
      - 6.5.3 Retrospective: Sprints/Sprint4/Retrospective.md
    - 6.6 Sprint 5: 
      - 6.6.1 Planning: Sprints/Sprint5/Planning.md
      - 6.6.2 Review: Sprints/Sprint5/Review.md
      - 6.6.3 Retrospective: Sprints/Sprint5/Retrospective.md
    - 6.7 Sprint 6: 
      - 6.7.1 Planning: Sprints/Sprint6/Planning.md
      - 6.7.2 Review: Sprints/Sprint6/Review.md
      - 6.7.3 Retrospective: Sprints/Sprint6/Retrospective.md
    - 6.8 Sprint 7: 
      - 7.8.1 Planning: Sprints/Sprint7/Planning.md
      - 7.8.2 Review: Sprints/Sprint7/Review.md
      - 7.8.3 Retrospective: Sprints/Sprint7/Retrospective.md
    - 6.9 Sprint 8: 
      - 8.8.1 Planning: Sprints/Sprint8/Planning.md
      - 8.8.2 Review: Sprints/Sprint8/Review.md
      - 8.8.3 Retrospective: Sprints/Sprint8/Retrospective.md 
    - 6.10 Sprint 9: 
      - 9.8.1 Planning: Sprints/Sprint8/Planning.md
      - 9.8.2 Review: Sprints/Sprint8/Review.md
      - 9.8.3 Retrospective: Sprints/Sprint8/Retrospective.md 
    - 6.11 Sprint 10: 
      - 10.8.1 Planning: Sprints/Sprint10/Planning.md
      - 10.8.2 Review: Sprints/Sprint10/Review.md
      - 10.8.3 Retrospective: Sprints/Sprint10/Retrospective.md 

extra_css:
  - extra.css 