site_name: VaiPelaSombra
theme:
  name: material
  language: pt-BR
  logo: ../../img/logo_completa.png
  favicon: ../../img/logo_completa.png

  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra 


nav:
  - Sobre o projeto: index.md
  - 1. Análise de Requisitos: Requisitos/index.md
  - 2. FrontEnd: 
    - 2.1. FrontEnd Estrutura: FrontEnd/index.md
    - 2.2. FrontEnd Dojos: FrontEnd/Dojos/index.md
    - 2.3. Guia de Estilo: FrontEnd/DocGuiaDeEstilo/index.md
  - 3. BackEnd: 
    - 3.1. BackEnd Estrutura: BackEnd/index.md
    - 3.2. BackEnd Dojos: BackEnd/Dojos/index.md
  - 4. Documento de Arquitetura: DocArquitetura/DocumentoArquitetura.md
  - 5. Acompanhamento de Valor Agregado: DocValorAgregado/index.md
  - 6. Guia de Contribuição: DocGuiaDeContribuicao/index.md

extra_css:
  - extra.css 